Fix

diff --git a/.github/workflows/create-tag-release.yml b/.github/workflows/create-tag-release.yml
--- a/.github/workflows/create-tag-release.yml
+++ b/.github/workflows/create-tag-release.yml
@@ -1,113 +1,130 @@
-# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
-
 name: Create tag release
-
-env:
-  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
-  DOTNET_NOLOGO: true
-  PackageName: "EcoCode"
-
-on:    
+on:
   push:
     tags:
       - '[0-9]+.[0-9]+.[0-9]+'
       - '[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
-
 permissions:
   actions: write
   contents: write
+env:
+  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
+  DOTNET_NOLOGO: true
 
 jobs:
   versioning:
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.versioning.outputs.version }}
-      prerelease: ${{ steps.versioning.outputs.pre_release }}
+      tag: ${{ steps.versioning.outputs.tag }}
+      version: ${{ steps.versioning.outputs.version }} # same as tag but without the -betaN part at the end, if present
     steps:
-      - name: Checkout branch
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 # Necessary to fetch tags
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 0 # Necessary to fetch tags
 
-      - name: Versioning analysis
-        id: versioning
-        run: |
-          VERSION=${GITHUB_REF#refs/tags/}
-          echo "Full version tag: $VERSION"
+    - id: versioning
+      run: |
+        TAG=${GITHUB_REF#refs/tags/}
+        echo "Full version tag: $TAG"
 
-          TAG_COMMIT=$(git rev-list -n 1 $VERSION)
-          MAIN_BRANCH_COMMIT=$(git rev-parse origin/main)
-          if ! git merge-base --is-ancestor $TAG_COMMIT $MAIN_BRANCH_COMMIT; then
-            echo "Tag is not on main branch, stopping workflow."
-            exit 1
-          fi
+        TAG_COMMIT=$(git rev-list -n 1 $TAG)
+        MAIN_BRANCH_COMMIT=$(git rev-parse origin/${{ github.event.repository.default_branch }})
+        if ! git merge-base --is-ancestor $TAG_COMMIT $MAIN_BRANCH_COMMIT; then
+          echo "Tag is not on the main branch, stopping workflow."
+          exit 1
+        fi
 
-          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+(-beta[0-9]+)?$ ]]; then
-            echo "pre_release=$( [[ -n ${BASH_REMATCH[1]} ]] && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT
-          else
-            echo "Error: Tag does not match the expected format 'X.Y.Z' or 'X.Y.Z-betaN'"
-            exit 1
-          fi
-          echo "version=$VERSION" >> $GITHUB_OUTPUT
+        if [[ $TAG =~ ^([0-9]+\.[0-9]+\.[0-9]+)(-beta[0-9]+)?$ ]]; then
+          echo "version=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
+          echo "tag=$TAG" >> $GITHUB_OUTPUT
+        else
+          echo "Error: Tag does not match the expected format 'X.Y.Z' or 'X.Y.Z-betaN'"
+          exit 1
+        fi
 
-  publish-nuget:
+  build-nuget:
     needs: versioning
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout branch
-        uses: actions/checkout@v4
+    - uses: actions/checkout@v4
+    - uses: actions/setup-dotnet@v4
+    - run: dotnet restore NoVsix.slnf
+    - run: dotnet build NoVsix.slnf -c Release --no-restore
+    - run: dotnet test NoVsix.slnf -c Release --no-build --logger "trx;LogFileName=test_results.trx"
+    - run: dotnet pack NoVsix.slnf -c Release --no-build -o ./nupkg -p:Version=${{ needs.versioning.outputs.tag }}
+    - uses: actions/cache/save@v4
+      with:
+        path: nupkg
+        key: cache-${{ github.sha }}
 
-      - name: Set up .NET
-        uses: actions/setup-dotnet@v4
-
-      - name: Build
-        run: dotnet build NoVsix.slnf -c Release
-
-      - name: Run tests
-        run: dotnet test NoVsix.slnf -c Release --no-build --logger "trx;LogFileName=test_results.trx"
-
-      - name: Create NuGet package
-        run: dotnet pack NoVsix.slnf -c Release --no-build --output ./nupkg /p:Version=${{ needs.versioning.outputs.version }}
-
-      - name: Publish NuGet package
-        run: dotnet nuget push ./nupkg/*.nupkg -k "${{ secrets.NUGET_API_KEY }}" -s https://api.nuget.org/v3/index.json
-
-  publish-vsix:
+  build-vsix:
     needs: versioning
     runs-on: windows-latest
     steps:
-      - name: Checkout branch
-        uses: actions/checkout@v4
+    - uses: actions/checkout@v4
+    - run: | # Update VSIX version
+        [xml]$manifest = Get-Content "src\EcoCode.Vsix\source.extension.vsixmanifest"
+        $identity = $manifest.SelectSingleNode("//*[local-name()='Identity']")
+        if ($identity -ne $null) {
+            $identity.Version = "${{ needs.versioning.outputs.version }}"
+        }
+        $manifest.Save("src\EcoCode.Vsix\source.extension.vsixmanifest")
+    - uses: actions/setup-dotnet@v4
+    - run: dotnet restore VsixOnly.slnf
+    - uses: microsoft/setup-msbuild@v2
+    - run: msbuild VsixOnly.slnf "-p:OutputPath=..\..\vsix;Configuration=Release"
+    - uses: actions/cache/save@v4
+      with:
+        path: vsix
+        key: cache-${{ github.sha }}
+        enableCrossOsArchive: true
 
-      - name: Update VSIX version
-        run: |
-          path="src/EcoCode.Vsix/source.extension.vsixmanifest"
-          version="${{ needs.versioning.outputs.version }}"
-          sed -i -E "s/(<Identity[^>]+Version=\")[^\"]+/\1$version/" $path
-
-      - name: Set up .NET
-        uses: actions/setup-dotnet@v4
-
-      - name: Setup MSBuild
-        uses: microsoft/setup-msbuild@v2
-
-      - name: Build VSIX project
-        run: msbuild VsixOnly.slnf -property:Configuration=Release -nologo
-
-      # TODO : Publish VSIX to the marketplace
-
-  create-release:
-    needs: [versioning, publish-nuget, publish-vsix]
+  publish-nuget: # Only if both builds succeeded
+    needs: [versioning, build-nuget, build-vsix]
     runs-on: ubuntu-latest
     steps:
-      - name: Create GitHub Release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ needs.versioning.outputs.version }}
-          release_name: ${{ needs.versioning.outputs.version }}
-          commitish: "main"
-          draft: false
-          prerelease: ${{ needs.versioning.outputs.pre_release == 'true' }}
-          body: "Release of version ${{ needs.versioning.outputs.version }}"
+    - uses: actions/cache/restore@v4
+      with:
+        path: nupkg
+        key: cache-${{ github.sha }}
+    - run: dotnet nuget push EcoCode.${{ needs.versioning.outputs.tag }}.nupkg -k "${{ secrets.NUGET_API_KEY }}" -s https://api.nuget.org/v3/index.json  
+
+  publish-vsix: # Only if both builds succeeded, and the tag is not a pre-release
+    needs: [versioning, build-nuget, build-vsix]
+    if: ${{ needs.versioning.outputs.tag == needs.versioning.outputs.version }}
+    runs-on: windows-latest
+    steps:
+    - uses: actions/cache/restore@v4
+      with:
+        path: vsix
+        key: cache-${{ github.sha }}
+        enableCrossOsArchive: true
+    - uses: cezarypiatek/VsixPublisherAction@1.1
+      with:
+        extension-file: vsix\EcoCode.vsix
+        publish-manifest-file: vsix\publishManifest.json
+        personal-access-code: ${{ secrets.VSMARKETPLACE_API_KEY }}
+
+  create-release: # Only if both builds succeeded
+    needs: [versioning, build-nuget, build-vsix]
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/cache/restore@v4
+      with:
+        path: nupkg
+        key: cache-${{ github.sha }}
+    - uses: actions/cache/restore@v4
+      with:
+        path: vsix
+        key: cache-${{ github.sha }}
+        enableCrossOsArchive: true
+    - uses: softprops/action-gh-release@v2
+      with:
+        tag_name: ${{ needs.versioning.outputs.tag }}
+        name: ${{ needs.versioning.outputs.tag }}
+        draft: false
+        prerelease: ${{ needs.versioning.outputs.tag != needs.versioning.outputs.version }}
+        body: "Release of version ${{ needs.versioning.outputs.tag }}"
+        files: |
+          nupkg/**/EcoCode.${{ needs.versioning.outputs.tag }}.nupkg
+          vsix/EcoCode.vsix
